In [30]:
%load_ext autoreload
%autoreload 2
import numpy as np
import torch
from sims.tree import MCTS
from models.mlp import ConnectXModel
from games.connectx import ConnectXGame
from train import Trainer

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
game = ConnectXGame()
model = ConnectXModel(game.columns, game.columns, torch.device('mps'))
args = {
    'c_puct': 10.0,
    'num_simulations': 500,
    'num_iters': 1,
    'num_eps': 6400,
    'epochs': 500,
    'batch_size': 64,
    'checkpoint_path': './checkpoints',
    'device': 'mps'
}
trainer = Trainer(game, model, args)

In [19]:
trainer.exceute_episode()

[(array([0, 0, 0, 0], dtype=int16),
  array([0.00496, 0.01521, 0.97535, 0.00448]),
  1),
 (array([ 0,  0, -1,  0], dtype=int16),
  array([0.10851, 0.3239 , 0.     , 0.56759]),
  -1),
 (array([ 0,  0,  1, -1], dtype=int16),
  array([0.0299, 0.9701, 0.    , 0.    ]),
  1)]

In [4]:
trainer.learn()

1/1


Self Play: 100%|██████████| 6400/6400 [04:02<00:00, 26.37it/s]



Policy Loss 1.3149822052319844
Value Loss 0.6486598811546962
Examples:
tensor([0.1138, 0.1794, 0.5413, 0.1655], device='mps:0')
tensor([0.0000, 0.0000, 0.7820, 0.2180], device='mps:0')

Policy Loss 1.2016142171621322
Value Loss 0.3529689969494939
Examples:
tensor([0.0846, 0.1890, 0.5040, 0.2224], device='mps:0')
tensor([0.0980, 0.3960, 0.3640, 0.1420], device='mps:0')

Policy Loss 1.1419561201333999
Value Loss 0.2391562162194815
Examples:
tensor([0.0061, 0.0432, 0.7441, 0.2066], device='mps:0')
tensor([0.0000, 0.0000, 0.7820, 0.2180], device='mps:0')

Policy Loss 1.0991306929290294
Value Loss 0.18075675909950709
Examples:
tensor([0.3822, 0.0090, 0.3277, 0.2812], device='mps:0')
tensor([0.3860, 0.0000, 0.3320, 0.2820], device='mps:0')

Policy Loss 1.069793669382731
Value Loss 0.14514578092144803
Examples:
tensor([0.0947, 0.3875, 0.3765, 0.1413], device='mps:0')
tensor([0.0980, 0.3960, 0.3640, 0.1420], device='mps:0')

Policy Loss 1.0505362500084772
Value Loss 0.12120379702737813
Exampl

In [5]:
args['num_simulations'] = 100000
tree = MCTS(game, model, args)

In [6]:
state = game.get_init_board()
root = tree.run(state, 1)

In [ ]:
root

[0 0 0 0] Prior: 0.00 Count: 100000 Value: [0.9473999]

In [35]:
value = 0
for a, child in root.children.items():
    value += child.value_sum
value /= root.visit_count
value

array([-0.9474], dtype=float32)

In [ ]:
root.children

{0: [-1  0  0  0] Prior: 0.10 Count: 496 Value: [-0.35483307],
 1: [ 0 -1  0  0] Prior: 0.40 Count: 1521 Value: [-0.15581849],
 2: [ 0  0 -1  0] Prior: 0.36 Count: 97535 Value: [-0.9672118],
 3: [ 0  0  0 -1] Prior: 0.14 Count: 448 Value: [0.02232138]}

In [23]:
a1 = 2
root.children[a1].children

{0: [-1  0  1  0] Prior: 0.22 Count: 10585 Value: [1.],
 1: [ 0 -1  1  0] Prior: 0.34 Count: 31584 Value: [0.96922493],
 3: [ 0  0  1 -1] Prior: 0.44 Count: 55365 Value: [0.95983016]}

In [ ]:
a2 = 1
root.children[a1].children[a2].children

{0: [-1  0 -1  1] Prior: 0.95 Count: 2223 Value: [0.00044984],
 1: None Prior: 0.05 Count: 53141 Value: -1.0}